
services:
  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq: 


# !!!REMEMBER!!! -> en sonda buraya go için bir servis daha ekleyeceğim.