
services:
  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  s_api:
    container_name: c_api
    build: ./backend_go
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@s_rabbitmq:5672/
    depends_on:
      - s_rabbitmq
    command: go run cmd/api/main.go
    volumes:
      - ./backend_go:/app
  s_consumer:
    container_name: c_consumer
    build: ./backend_go
    environment:
      - RABBITMQ_URL=amqp://guest:guest@s_rabbitmq:5672/
    depends_on:
      - s_rabbitmq
    command: go run cmd/consumer/main.go
    volumes:
      - ./backend_go:/app

volumes:
  rabbitmq: